### PR TITLE
add output after run all

### PR DESCRIPTION
**Pull request by kozo2**

### CODE REVIEW

**Comment by vincentdavis** [comment]
Thanks for the work. A couple comments.
Can you combine lines of code that have no output. For example combine cells 3,4,5,6 into 1 code cell.
Is there an way to make the output of cell 18 ```human_pathways``` a little shorter, maybe print just a few pathways?
Thanks again.

**Comment by tiagoantao** [comment]
Many thanks @kozo2 for this. Adding to @vincentdavis comments, could I please ask you to submit a Python 3 version instead?

Thanks!!!!

**Comment by kozo2** [comment]
Hi, @vincentdavis @tiagoantao 
I
- [x] combined lines of code that have no output.
- [x] made the output of ```human_pathways``` a little shorter.
- [x] submitted a Python 3 version instead.

at https://github.com/kozo2/biopython-notebook/commit/7c6c0201eae7a8dc0d0384841fa77b9171687caa

**Comment by tiagoantao** [comment]
@kozo2 : Many thanks. I will merge this.

**Pull request merged**
